baseurl = "http://kono.sh/"
languageCode = "en-us"
title = "Bryan Konowitz"
theme = "casper"
paginate = 5
copyright = "All rights reserved - 2015"

[indexes]
   category = "categories"
   tag = "tags"

[params]
  description = "Solved by Code"
  author = "bkono"
  cover = "images/cover-work_stations_espresso-50p.jpg"
  githubName = "bkono"
  hideHUGOSupport = false

[params.authors]
  [params.authors.bkono]
    bio = "Bryan started off with a keyboard in his crib, and has kept a passion for technology all his life. When he's not trying to solve everyday problems through technology, he enjoys spending time with his wife and two kids."
    name = "Bryan Konowitz"
    location = "Las Vegas, Nv"
    website = "http://kono.sh"
  [params.authors.moofish32]
    name = "Michael Cowgill"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Github repos"
  weight = 100
  pre = "<h4>Follow me</h4>"
  url = "https://github.com/bkono"

[[menu.main]]
  name = "Email"
  weight = 109
  pre = "<h4>Contact me</h4>"
  url = "mailto:bryan@kono.sh"
