baseurl = "http://kono.sh/"
languageCode = "en-us"
title = "Bryan Konowitz"
theme = "casper"
paginate = 5
copyright = "All rights reserved - 2015"
PygmentsCodeFences = true
pygmentsstyle = "paraiso-dark"

[indexes]
   category = "categories"
   tag = "tags"
[params]
  description = "Solved by Code"
  author = "bkono"
  cover = "images/cover-work_stations_espresso-50p.jpg"
  githubName = "bkono"
  googleAnalyticsUserID = "UA-64072292-1"
  hideHUGOSupport = false

[[menu.main]]
  name = "Blog"
  weight = 1200
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Github repos"
  weight = 100
  url = "https://github.com/bkono"

[[menu.main]]
  name = "Email"
  weight = 99
  url = "mailto:bryan@kono.sh"

[[menu.main]]
  name = "Resume"
  weight = 98
  url = "/resume.html"

[[menu.main]]
  name = "Keybase"
  weight = 97
  url = "/keybase.txt"
